project:
  type: book

book:
  title: "Human Neuroimaging with MRI: A Primer"
  author:
    - Brian Wandell
    - Jonathan Winawer
  date: "06/01/2026"
  chapters:
    - index.qmd
    - part: "Instrumentation"
      chapters:
       - chapters/part1-instrumentation.qmd
       - chapters/ch01-big-iron.qmd
       - chapters/ch02-gradient-coils.qmd
       - chapters/ch03-rf-coils.qmd
       - chapters/ch04-safety.qmd
    - part: "Signals"
      chapters:
       - chapters/part2-signals.qmd
    - part: "Image Formation"
      chapters:
       - chapters/part3-imageformation.qmd
    - part: "Brain"
      chapters:
       - chapters/part4-brain.qmd
    - part: "Functional Signals"
      chapters:
       - chapters/part5-functionalsignals.qmd
    - part: "Data Analysis"
      chapters:
       - chapters/part6-dataanalysis.qmd
    - part: "Diffusion"
      chapters:
       - chapters/part7-diffusion.qmd
    - part: "qMRI"
      chapters:
       - chapters/part8-qmri.qmd
    - part: "Applications"
      chapters:
       - chapters/part9-applications.qmd
       
bibliography:
  - paperpile.bib
  - references.bib

crossref:
  chapters: true
  fig-prefix: "Figure"
  tbl-prefix: "Table"
  sec-prefix: "Section"
  
#  I am unsure about these formatting commands for the document.  Experimental.
format:
  html:
    toc: true
    layout: sidebar
    number-sections: true
    theme: cosmo   # flatly, yeti, sandstone, minty, cerulean, default
    fig-cap-location: margin
    render-on-save: true
    mathjax: "local"
    math: 
      number-sections: true
      number-equations: true
  pdf:
    documentclass: scrreprt
    toc: true
    toc-title: "Contents"
    toc-number-sections: true
    toc-number-depth: 2
    fig-caption: true
    number-sections: true
    number-depth: 2
    keep-tex: false
    latex-clean: true
    math:
      number-equations: true





