project:
  type: book

book:
  title: "Human Neuroimaging with MRI: A Primer"
  author:
    - Brian Wandell
    - Jonathan Winawer
  date: "06/01/2026"
  chapters:
    - index.qmd
    - part: chapters/part1-instrumentation.qmd
      chapters:
       - chapters/ch01-big-iron.qmd
       - chapters/ch02-gradient-coils.qmd
       - chapters/ch03-rf-coils.qmd
       - chapters/ch04-safety.qmd
    - part: chapters/part2-signals.qmd
      chapters:
       - chapters/ch05-mr-signal-fundamentals.qmd
       - chapters/ch06-macroscopic-model.qmd
       - chapters/ch07-t1-relaxation.qmd
       - chapters/ch08-t2-relaxation.qmd
       - chapters/ch09-mri-summary-spin-echo.qmd
       - chapters/ch10-pulse-sequences.qmd
       - chapters/ch11-physical-mechanisms.qmd
    - part: chapters/part3-imageformation.qmd
      chapters:
       - chapters/ch12-image-formation-principles.qmd
       - chapters/ch13-gradient-encoding-lauterbur.qmd
       - chapters/ch14-fourier-series-kspace.qmd
       - chapters/ch15-slice-selection.qmd
       - chapters/ch16-gradient-echo.qmd
       - chapters/ch17-imaging-within-slice.qmd
       - chapters/ch18-kspace-epi.qmd
       - chapters/ch19-image-quality.qmd
       - chapters/ch20-parallel-imaging.qmd
       - chapters/ch21-image-data-formats.qmd
    - part: chapters/part4-brain.qmd
      chapters: []
    - part: chapters/part5-functionalsignals.qmd
      chapters: []
    - part: chapters/part6-dataanalysis.qmd
      chapters: []
    - part: chapters/part7-diffusion.qmd
      chapters: []
    - part: chapters/part8-qmri.qmd
      chapters: []
    - part: chapters/part9-applications.qmd
      chapters: []
       
bibliography:
  - paperpile.bib
  - references.bib

crossref:
  chapters: true
  fig-prefix: "Figure"
  tbl-prefix: "Table"
  sec-prefix: "Section"
  
#  I am unsure about these formatting commands for the document.  Experimental.
format:
  html:
    toc: true
    layout: sidebar
    number-sections: true
    theme: cosmo   # flatly, yeti, sandstone, minty, cerulean, default
    fig-cap-location: margin
    render-on-save: true
    mathjax: "local"
    math: 
      number-sections: true
      number-equations: true
#  pdf:
#    documentclass: scrreprt
#    toc: true
#    toc-title: "Contents"
#    toc-number-sections: true
#    toc-number-depth: 2
#    fig-caption: true
#    number-sections: true
#    number-depth: 2
#    keep-tex: false
#    latex-clean: true
#    math:
#      number-equations: true





